### ISSUE TITLE
Start the animation from the previous data

### ISSUE THREAD

**Issue by Dhentai** [ps-cristopher/vue3-autocounter#2]
## Describe
After the instance is created, the animation will restart from startAmount every time the endAmount changes.

## Suggested solution
Add a prop to control whether the animation starts from the previous endAmount.

**Comment by ps-cristopher** [comment]
Yes, currently when you change the `endAmount`the counting should be restarted in order to recalculate the duration for each iteration, I will consider this as an enhancement to prevent the counting restart until the previous is finished, this behavior could be controlled with a prop how @Dhentai suggested. Thank you @Dhentai!!

**Comment by ps-cristopher** [comment]
No more users have requested this enhancement, so I'll discard it and close this issue.
Thanks!
